puts "🌱 Seeding..."
puts "Deleting old data..."
User.destroy_all
Ingredient.destroy_all
Recipe.destroy_all
RecipeIngredient.destroy_all

puts "Creating users..."
dan = User.create(username: "DannyLeeBeasley", password: "TrickyPassword13!")
katie = User.create(username: "KatieBeasley", password: "NeverGuess27!")

puts "Creating ingredients..."
salt = Ingredient.create(name: "Salt", image:"https://w2.chabad.org/media/images/745/WiIZ7453042.jpg")
fresh_cracked_black_pepper = Ingredient.create(name: "Fresh Cracked Black Pepper", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/1280x1280/products/5091/9704/black-pepper-cafe-restaraunt-grind__51833.1540751690.jpg?c=2")
crushed_red_pepper = Ingredient.create(name: "Crushed Red Pepper", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/5097/9708/crushed-red-pepper__12390.1540713424.jpg?c=2")
garlic_powder = Ingredient.create(name: "Garlic Powder", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/4950/10693/garlic-powder__80779.1540713339.jpg?c=2")
chili_powder = Ingredient.create(name: "Chili Powder", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/4871/11141/ChiliPowder__58800.1621928606.jpg?c=2")
ground_cumin = Ingredient.create(name: "Ground Cumin", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/4904/9607/ground-cumin-powder__07473.1540713307.jpg?c=2")
ground_cayenne = Ingredient.create(name: "Ground Cayenne", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/5098/9709/red-cayene-pepper-ground__88154.1540751694.jpg?c=2")
ground_allspice = Ingredient.create(name: "Ground Allspice", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/4752/9542/ground-allspice__63984.1540713215.jpg?c=2") 
sweet_paprika = Ingredient.create(name: "Sweet Paprika", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/5080/11023/paprika-hungarian-sweet__83203.1580303031.jpg?c=2")
smoked_paprika = Ingredient.create(name: "Smoked Paprika", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/5082/10749/paprika-smoked-sweet__12660.1540776008.jpg?c=2")
ground_cinnamon = Ingredient.create(name: "Ground Cinnamon", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/4882/9928/saigon-cinnamon__98142.1540713294.jpg?c=2")
dried_oregano = Ingredient.create(name: "Dried Oregano", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/5075/9695/mexican-oregano-greek-cut__33239.1540713410.jpg?c=2")
dried_basil = Ingredient.create(name: "Dried Basil", image: "https://cdn11.bigcommerce.com/s-9d454/images/stencil/2560w/products/4781/9557/dried-basil__03886.1540713234.jpg?c=2")

fresh_parsley = Ingredient.create(name: "Fresh Parsley", image: "https://chefsmandala.com/wp-content/uploads/2018/03/Parsley-Fresh-Flat-IT.jpg")
fresh_cilantro = Ingredient.create(name: "Fresh Cilantro", image: "https://cdn.shopify.com/s/files/1/0095/6258/7195/products/cilantro.jpg?v=1575429635")
fresh_mint = Ingredient.create(name: "Fresh Mint", image: "https://kitchenlily.com/wp-content/uploads/2020/01/How-to-store-mint-keep-it-fresh-for-long.jpg")
fresh_oregano = Ingredient.create(name: "Fresh Oregano", image: "https://envato-shoebox-0.imgix.net/25cf/1526-8c01-4216-a70d-c8c4a535866b/Canon_090919_0767.jpg?auto=compress%2Cformat&fit=max&mark=https%3A%2F%2Felements-assets.envato.com%2Fstatic%2Fwatermark2.png&markalign=center%2Cmiddle&markalpha=18&w=700&s=4b1919e16bdd65af461609858d6dfbb1")
fresh_basil = Ingredient.create(name: "Fresh Basil", image: "https://cdn.shopify.com/s/files/1/0257/5676/2202/products/AdobeStock_2353758_1024x1024.jpg?v=1579366807")

baby_spinach = Ingredient.create(name: "Baby Spinach", image: "https://solidstarts.com/wp-content/uploads/Spinach-for-Babies-scaled.jpg")
white_onion = Ingredient.create(name: "White Onion", image: "https://i5.walmartimages.com/asr/da6d7d4b-2004-4603-ad6a-38664278af05_1.cbba93cf3e8555bb2386d1f508ac2dd7.jpeg?odnWidth=612&odnHeight=612&odnBg=ffffff")
shallots = Ingredient.create(name: "Shallots", image: "https://assets.bonappetit.com/photos/57bf2ffc6a6acdf3485df79f/master/w_1600%2Cc_limit/shallot-silo.jpg")
green_onion = Ingredient.create(name: "Green Onion", image: "https://d2d8wwwkmhfcva.cloudfront.net/800x/d2lnr5mha7bycj.cloudfront.net/product-image/file/large_1078b6b8-f905-4e82-bb5d-f2d613bfa162.jpg")
garlic = Ingredient.create(name: "Garlic", image: "https://www.mcgill.ca/oss/files/oss/styles/hd/public/garlic.jpg?itok=GlTU4c3n&timestamp=1486146272")
tomatillos = Ingredient.create(name: "Tomatillos", image: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F19%2F2019%2F10%2F01%2Ftomatillos-2000.jpg")
red_bell_pepper = Ingredient.create(name: "Red Bell Pepper", image: "https://m.media-amazon.com/images/S/assets.wholefoodsmarket.com/PIE/product/56ea234b340e3111001bffd6_365_-red-bell-peppers.1-copy.jpg")
yellow_bell_pepper = Ingredient.create(name: "Yellow Bell Pepper", image: "https://d2d8wwwkmhfcva.cloudfront.net/800x/d2lnr5mha7bycj.cloudfront.net/product-image/file/large_4fdf8171-7dae-458a-a500-ae2969af48fd.jpg")
fresh_fresno = Ingredient.create(name: "Fresh Fresno", image: "https://d2d8wwwkmhfcva.cloudfront.net/800x/d2lnr5mha7bycj.cloudfront.net/product-image/file/large_5526c385-f34d-4c40-a6e8-8dcf7dae5c4a.jpg")
fresh_jalepeno = Ingredient.create(name: "Fresh Jalepeno", image: "https://holylandbrand.com/shop/wp-content/uploads/2020/09/jalapeno.jpg")
zucchini = Ingredient.create(name: "Zucchini", image: "https://i5.walmartimages.com/asr/33be66a0-cbfc-4d37-bd3f-38b06cfe39d6_1.a3a9085102f3a8f794f5965143a363c1.jpeg?odnWidth=612&odnHeight=612&odnBg=ffffff")
carrots = Ingredient.create(name: "Carrots", image: "https://media.istockphoto.com/photos/fresh-carrots-isolated-on-white-background-picture-id545454816?k=20&m=545454816&s=612x612&w=0&h=zTbL2GTPiWKU7kNyC1mqsQfbBvQIQNKtRgm_uLzUKkk=")

lime = Ingredient.create(name: "Lime", image: "https://chefsmandala.com/wp-content/uploads/2018/03/Lime-Whole-Half.jpg")

diced_tomatoes = Ingredient.create(name: "Diced Tomatoes", image: "https://www.jessicagavin.com/wp-content/uploads/2020/08/types-of-canned-tomatoes-diced-600x400.jpg")
chipotle_in_adobo = Ingredient.create(name: "Chipotle In Adobo", image: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2020%2F01%2FGettyImages-625853150-2000.jpg&q=85")
black_beans = Ingredient.create(name: "Black Beans", image: "https://www.isabeleats.com/wp-content/uploads/2020/01/how-to-cook-canned-black-beans-small-3.jpg")
kidney_beans = Ingredient.create(name: "Kidney Beans", image: "https://static8.depositphotos.com/1009864/929/i/950/depositphotos_9293175-stock-photo-canned-red-kidney-beans.jpg")

all_purpose_flour = Ingredient.create(name: "All Purpose Flour", image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/flour-in-bowl-bread-flour-vs-all-purpose-flour-1611940896.jpg?crop=0.631xw:1.00xh;0.311xw,0&resize=640:*")
panko_breadcrumbs = Ingredient.create(name: "Panko Breadcrumbs", image: "https://www.chopstickchronicles.com/wp-content/uploads/2019/10/Panko-LR-edited-10-2-e1571979163688-500x500.jpg")
large_flour_tortillas = Ingredient.create(name: "Large Flour Tortillas", image: "https://www.cookingclassy.com/wp-content/uploads/2020/03/flour-tortillas-11.jpg")
wide_rice_noodles = Ingredient.create(name: "Wide Rice Noodles", image: "https://www.westpointnaturals.com/wp-content/uploads/2017/10/White-Rice-Noodles-Wide.jpg")
cheese_tortellini = Ingredient.create(name: "Cheese Tortellini", image: "https://www.maxdelivery.com/nkz/gifs/60084497.jpg")

parmesan = Ingredient.create(name: "Parmesan Cheese", image: "https://oliveoilmarketplace.com/wp-content/uploads/imported/Parmesan.jpg")
monterey_jack = Ingredient.create(name: "Monterey Jack Cheese", image: "https://static.onecms.io/wp-content/uploads/sites/9/2017/06/how-monterey-jack-got-its-name-fwx.jpg")

ground_beef = Ingredient.create(name: "Ground Beef", image: "https://embed.widencdn.net/img/beef/4hh1pywcnj/800x600px/Grind_Fine_85.psd?keep=c&u=7fueml")
italian_sausage = Ingredient.create(name: "Italian Sausage", image: "https://tasteofartisan.com/wp-content/uploads/2019/12/Italian-sausage-recipe-2-500x375.jpg")
skirt_steak = Ingredient.create(name: "Skirt Steak", image: "https://www.farm2fork.co.uk/wp-content/uploads/2016/05/Beef-Skirt-Steak.jpg")
salmon_filet = Ingredient.create(name: "Salmon Filet", image: "https://cdn.shopify.com/s/files/1/0066/8493/4205/products/scottish_salmon_2_large.jpg?v=1541976322")
shredded_rotisserie_chicken = Ingredient.create(name: "Shredded Rotisserie Chicken", image: "https://www.gimmesomeoven.com/wp-content/uploads/2013/09/Easy-Slow-Cooker-Shredded-Chicken-1.jpg")

conola_oil = Ingredient.create(name: "Canola Oil", image: "https://naturallivingfamily.com/wp-content/uploads/2017/05/canola-oil-nutrition-facts-pros-cons-what-you-need-to-know.jpg")
refined_sesame_oil = Ingredient.create(name: "Refined Sesame Oil", image: "https://www.gardeningknowhow.com/wp-content/uploads/2018/07/sesame-oil.jpg")
unsalted_butter = Ingredient.create(name: "Unsalted Butter", image: "https://fortmyersoliveoil.com/wp-content/uploads/2016/06/butter_2.jpg")
evoo = Ingredient.create(name: "Extra Virgin Olive Oil", image: "https://media.istockphoto.com/photos/olives-and-oil-bottle-picture-id174778941?k=20&m=174778941&s=612x612&w=0&h=Vwt7CdzKAaZJTfuA6VAPVP05cLoyMPxF2GGLkSfhqBw=")

red_wine_vinegar = Ingredient.create(name: "Red Wine Vinegar", image: "https://mk0nutritionadvxtj6i.kinstacdn.com/wp-content/uploads/2017/07/composition-of-red-wine-vinegar.jpg")
chicken_broth = Ingredient.create(name: "Chicken Broth", image: "https://keviniscooking.com/wp-content/uploads/2020/04/How-to-Make-Chicken-Stock-5.jpg")
dijon_mustard = Ingredient.create(name: "Dijon Mustard", image: "https://www.thespruceeats.com/thmb/POjGKVz1EfRY5F3LsAQjUgPJzaA=/450x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-56110366-588542c43df78c2ccdafa3bc.jpg")
soy_sauce = Ingredient.create(name: "Soy Sauce", image: "https://thenymelrosefamily.com/wp-content/uploads/2019/11/homemade-soy-sauce-in-a-white-dish.jpg")
oyster_sauce = Ingredient.create(name: "Oyster Sauce", image: "https://fullofplants.com/wp-content/uploads/2021/04/vegan-oyster-sauce-vegetarian-mushroom-strir-fry-sauce-thumb-2.jpg")
fish_sauce = Ingredient.create(name: "Fish Sauce", image: "https://miro.medium.com/max/700/1*TJiNLOvmLBDrisNShh9B_g.jpeg")
honey = Ingredient.create(name: "Honey", image: "https://www.jessicagavin.com/wp-content/uploads/2019/02/honey-pin.jpg")

light_brown_sugar = Ingredient.create(name: "Light Brown Sugar", image: "https://woodlandfoods.com/img/WF_Images/H388-light-brown-sugar-main.jpg")
hershey_kisses = Ingredient.create(name: "Hershey Kisses", image: "https://www.candywarehouse.com/item-images/125880-01_hersheys-kisses-large-milk-chocolate-kisses-6-piece-box.jpg?resizeid=102&resizeh=500&resizew=500")
instant_coffee = Ingredient.create(name: "Instant Coffee", image: "https://www.takaski.com/wp-content/uploads/2019/06/UCC-The-Blend-114-Instant-Coffee-Made-in-Japan3.jpg")
red_wine = Ingredient.create(name: "Red Wine", image: "https://cdn.hiconsumption.com/wp-content/uploads/2017/02/Sempli-Vaso-Vino-Wine-Decanter.jpg")
light_lager = Ingredient.create(name: "Light Lager", image: "https://cdn.shopify.com/s/files/1/2785/6868/products/420x-ThisBeersForYou_ba6bd4e5-21b8-41d6-a21d-d01b47f2adbd_x700.jpg?v=1605567722")

puts "Creating Recipes..."
tortellini_soup = Recipe.create(user_id: 1, name: "Tortellini Soup", image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2014/2/19/0/FN_Spinach-Tortellini-Soup_s4x3.jpg.rend.hgtvcom.826.620.suffix/1392869571244.jpeg", description: "Papaw's recipe; a favorite of his in his workplace cafeteria, he ate it every week and tried to recreate it until he honed in on this recipe.", instructions:"Brown sausage in 5-6 quart pan; drain. Add onion and cook for a few minutes until slightly translucent. Add garlic, basil, and oregano and cook for a minute or two until garlic is fragrant. Add broth and tomatoes and bring to a boil. Reduce heat and simmer for 2-3 hours. 15 minutes before serving, bring back to a boil and add the tortellini and chopped spinach. Boil gently until tortellini is done.")
enchiladas = Recipe.create(user_id: 2, name: "Chicken Enchiladas Roasted Tomatillo Salsa", image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2007/2/22/0/tu0203_enchilada.jpg.rend.hgtvcom.826.620.suffix/1382538510662.jpeg", description: "The roasted vegetables in these enchiladas create a depth of flavor that you will just get lost in.", instructions:"Preheat oven to 400 degrees F. On a baking tray, roast tomatillos, onion, garlic, and jalapenos for 12 to 15 minutes. Transfer the roasted vegetables and any juices on the bottom of the tray to a food processor. Add the cumin, salt, cilantro, and lime juice and pulse mixture until well combined but still chunky. Meanwhile, heat a 2 count of olive oil in a medium saucepan over medium heat. Add the onion and cook until soft and caramelized - this should take 5 to 7 minutes. Add the garlic and cumin then cook for a further minute. Sprinkle on the flour and stir to ensure the flour doesn't burn then gradually add the chicken stock to make a veloute. Continue stirring over a low simmer until the flour cooks and the liquid thickens. Turn off the heat, add half of the roasted tomatillo chile salsa, some additional fresh chopped cilantro, and fold in the shredded chicken meat. Season, to taste, with salt and pepper. Change the temperature of the oven to 350 degrees F and begin assembling the dish. Take a large flameproof baking dish and smear the bottom with some of the reserved tomatillo salsa. Now take the flour tortillas and briefly flash them over the stove-top flame (or put them briefly under the broiler if using an electric stove). Using a shallow bowl, coat each tortilla lightly with the reserved salsa mix. Put a scoop of the shredded chicken-enchilada mix on top of the tortilla followed by a sprinkle of the shredded cheese. Fold the tortilla over the filling and roll like a cigar to enclose it. Using a spatula place the tortillas in the baking dish and continue to do the same with all the tortillas. Finally pour over some more of the salsa and top with the remaining shredded cheese. Bake uncovered for about 30 minutes until bubbly and cracked on top. Garnish with cilantro and tomato.")
skirt_steak_chimichurri = Recipe.create(user_id: 1, name: "Grilled Skirt Steak with Green and Smokey Red Chimichurri", image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/7/22/0/QF0111H_grilled-skirt-steak-with-green-and-smokey-red-chimichurri_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371599786530.jpeg", description: "The red and green chimichurri compliment each other beuatifully. Perfect for an outdoor summer dinner date!", instructions:"For the green chimichurri: Combine the parsley, mint, oregano, canola oil, vinegar, red pepper flakes, and garlic in a food processor and process until smooth. Put the steak in a large baking dish, add the green chimichurri and turn to coat. Cover and refrigerate for at least 4 hours and up to 24 hours. Remove the steak from the marinade and place it on a plate 30 minutes before grilling. For the red chimichurri: Using a mortar and pestle, combine the parsley, olive oil, vinegar, oregano, chipotle, paprika, red pepper flakes, garlic, and some salt and pepper. Preheat a charcoal or gas grill to high heat. Sprinkle the steaks with salt and pepper on both sides. Grill until charred on both sides and cooked to medium-rare doneness, about 5 minutes per side. Remove from the grill and let rest on a cutting board for 5 minutes. Cut the meat across the grain into thin slices, top with the red chimichurri, and garnish with fresh parsley leaves.")
thai_drunken_noodles = Recipe.create(user_id: 2, name: "Thai Drunken Noodles", image: "https://data.thefeedfeed.com/static/2020/02/28/15829232455e597dede79c2.jpg", description: "Get your veggies in AND get your pasta fix with this gluten free comfort bowl!", instructions:"Cook the rice noodles according to package directions; drain. Combine the soy sauce, oyster sauce, fish sauce, honey, and 1/3 cup water in a bowl. Heat the oil in a large skillet over medium heat. When the oil shimmers, add the chicken. Season with black pepper and brown all over. Add the shallots, garlic, Fresno peppers, and green onions. Cook another 2-3 minutes, until the shallots are soft and the garlic is fragrant. Add the zucchini and bell peppers, cook another 5 minutes, until the vegetables have softened. Pour in the sauce and bring to a boil over medium-high heat and cook until the sauce coats the chicken, about 5 minutes. Stir in the noodles, carrots, and basil. Toss to combine, cooking another 3-5 minutes until the sauce coats the noodles. Serve the noodles warm, topped with additional basil.")

puts "Creating Recipe Ingredients..."
tortellini_soup_salt = RecipeIngredient.create(recipe_id: 1, ingredient_id: 1, amount: 1, unit: "Tsp")
tortellini_soup_fresh_cracked_black_pepper = RecipeIngredient.create(recipe_id: 1, ingredient_id: 2, amount: 1, unit: "Tsp")
tortellini_soup_dried_oregano = RecipeIngredient.create(recipe_id: 1, ingredient_id: 12, amount: 1, unit: "Tsp")
tortellini_soup_dried_basil = RecipeIngredient.create(recipe_id: 1, ingredient_id: 13, amount: 1, unit: "Tsp")
tortellini_soup_baby_spinach = RecipeIngredient.create(recipe_id: 1, ingredient_id: 19, amount: 2, unit: "Cups")
tortellini_soup_white_onion = RecipeIngredient.create(recipe_id: 1, ingredient_id: 20, amount: 1, unit: "")
tortellini_soup_garlic = RecipeIngredient.create(recipe_id: 1, ingredient_id: 23, amount: 2, unit: "Cloves")
tortellini_soup_diced_tomatoes = RecipeIngredient.create(recipe_id: 1, ingredient_id: 32, amount: 60, unit: "Oz")
tortellini_soup_cheese_tortellini = RecipeIngredient.create(recipe_id: 1, ingredient_id: 40, amount: 12, unit: "Oz")
tortellini_soup_italian_sausage = RecipeIngredient.create(recipe_id: 1, ingredient_id: 44, amount: 1, unit: "Lbs")
tortellini_soup_extra_virgin_olive_oil = RecipeIngredient.create(recipe_id: 1, ingredient_id: 51, amount: 2, unit: "Tbls")
tortellini_soup_chicken_broth = RecipeIngredient.create(recipe_id: 1, ingredient_id: 53, amount: 48, unit: "Oz")

enchiladas_tomatillos = RecipeIngredient.create(recipe_id: 2, ingredient_id: 24, amount: 1, unit: "Lbs")
enchiladas_white_onion = RecipeIngredient.create(recipe_id: 2, ingredient_id: 20, amount: 1.5, unit: "")
enchiladas_garlic = RecipeIngredient.create(recipe_id: 2, ingredient_id: 23, amount: 7, unit: "Cloves")
enchiladas_fresh_jalepeno = RecipeIngredient.create(recipe_id: 2, ingredient_id: 28, amount: 2, unit: "")
enchiladas_ground_cumin = RecipeIngredient.create(recipe_id: 2, ingredient_id: 6, amount: 3.5, unit: "Tsp")
enchiladas_salt = RecipeIngredient.create(recipe_id: 2, ingredient_id: 1, amount: 3, unit: "Tsp")
enchiladas_fresh_cilantro = RecipeIngredient.create(recipe_id: 2, ingredient_id: 15, amount: 1, unit: "Cups")
enchiladas_lime = RecipeIngredient.create(recipe_id: 2, ingredient_id: 31, amount: 0.5, unit: "")
enchiladas_extra_virgin_olive_oil = RecipeIngredient.create(recipe_id: 2, ingredient_id: 51, amount: 2, unit: "Tbls")
enchiladas_all_purpose_flour = RecipeIngredient.create(recipe_id: 2, ingredient_id: 36, amount: 0.25, unit: "Cups")
enchiladas_chicken_broth = RecipeIngredient.create(recipe_id: 2, ingredient_id: 53, amount: 2, unit: "Cups")
enchiladas_shredded_rotisserie_chicken = RecipeIngredient.create(recipe_id: 2, ingredient_id: 47, amount: 3, unit: "Cups")
enchiladas_fresh_cracked_black_pepper = RecipeIngredient.create(recipe_id: 2, ingredient_id: 2, amount: 2, unit: "Tsp")
enchiladas_large_flour_tortillas = RecipeIngredient.create(recipe_id: 2, ingredient_id: 38, amount: 10, unit: "")
enchiladas_monterey_jack_cheese = RecipeIngredient.create(recipe_id: 2, ingredient_id: 42, amount: 0.5, unit: "Lbs")

skirt_steak_chimichurri_skirt_steak = RecipeIngredient.create(recipe_id: 3, ingredient_id: 45, amount: 1.5, unit: "Lbs")
skirt_steak_chimichurri_fresh_parsley = RecipeIngredient.create(recipe_id: 3, ingredient_id: 14, amount: 3, unit: "Cups")
skirt_steak_chimichurri_fresh_mint = RecipeIngredient.create(recipe_id: 3, ingredient_id: 16, amount: 0.5, unit: "Cups")
skirt_steak_chimichurri_fresh_oregano = RecipeIngredient.create(recipe_id: 3, ingredient_id: 17, amount: 0.5, unit: "Cups")
skirt_steak_chimichurri_canola_oil = RecipeIngredient.create(recipe_id: 3, ingredient_id: 48, amount: 0.5, unit: "Cups")
skirt_steak_chimichurri_red_wine_vinegar = RecipeIngredient.create(recipe_id: 3, ingredient_id: 52, amount: 0.25, unit: "Cups")
skirt_steak_chimichurri_crushed_red_pepper = RecipeIngredient.create(recipe_id: 3, ingredient_id: 3, amount: 1.5, unit: "Tsp")
skirt_steak_chimichurri_garlic = RecipeIngredient.create(recipe_id: 3, ingredient_id: 23, amount: 11, unit: "Cloves")
skirt_steak_chimichurri_extra_virgin_olive_oil = RecipeIngredient.create(recipe_id: 3, ingredient_id: 51, amount: 0.5, unit: "Cups")
skirt_steak_chimichurri_fresh_oregano_finely_chopped = RecipeIngredient.create(recipe_id: 3, ingredient_id: 17, amount: 2, unit: "Tbls")
skirt_steak_chimichurri_chipotle_in_adobo = RecipeIngredient.create(recipe_id: 3, ingredient_id: 33, amount: 1, unit: "Tlbs")
skirt_steak_chimichurri_smoked_paprika = RecipeIngredient.create(recipe_id: 3, ingredient_id: 10, amount: 1, unit: "Tbls")
skirt_steak_chimichurri_salt = RecipeIngredient.create(recipe_id: 3, ingredient_id: 1, amount: 2, unit: "Tbls")
skirt_steak_chimichurri_fresh_cracked_black_pepper = RecipeIngredient.create(recipe_id: 3, ingredient_id: 2, amount: 1, unit: "Tbls")

thai_drunken_noodles_wide_rice_noodles = RecipeIngredient.create(recipe_id: 4, ingredient_id: 39, amount: 8, unit: "Oz")
thai_drunken_noodles_soy_sauce = RecipeIngredient.create(recipe_id: 4, ingredient_id: 55, amount: 0.33, unit: "Cup")
thai_drunken_noodles_oyster_sauce = RecipeIngredient.create(recipe_id: 4, ingredient_id: 56, amount: 3, unit: "Tbls")
thai_drunken_noodles_fish_sauce = RecipeIngredient.create(recipe_id: 4, ingredient_id: 57, amount: 1, unit: "Tbls")
thai_drunken_noodles_honey = RecipeIngredient.create(recipe_id: 4, ingredient_id: 58, amount: 2, unit: "Tsp")
thai_drunken_noodles_refined_sesame_oil = RecipeIngredient.create(recipe_id: 4, ingredient_id: 49, amount: 2, unit: "Tbsp")
thai_drunken_noodles_shredded_rotisserie_chicken = RecipeIngredient.create(recipe_id: 4, ingredient_id: 47, amount: 1, unit: "Cup")
thai_drunken_noodles_shallots = RecipeIngredient.create(recipe_id: 4, ingredient_id: 21, amount: 2, unit: "")
thai_drunken_noodles_garlic = RecipeIngredient.create(recipe_id: 4, ingredient_id: 23, amount: 3, unit: "Cloves")
thai_drunken_noodles_fresh_fresno = RecipeIngredient.create(recipe_id: 4, ingredient_id: 27, amount: 2, unit: "")
thai_drunken_noodles_zucchini = RecipeIngredient.create(recipe_id: 4, ingredient_id: 29, amount: 1, unit: "")
thai_drunken_noodles_red_bell_pepper = RecipeIngredient.create(recipe_id: 4, ingredient_id: 25, amount: 1, unit: "")
thai_drunken_noodles_carrots = RecipeIngredient.create(recipe_id: 4, ingredient_id: 30, amount: 2, unit: "")
thai_drunken_noodles_fresh_basil = RecipeIngredient.create(recipe_id: 4, ingredient_id: 18, amount: 1, unit: "Cup")
thai_drunken_noodles_green_onion = RecipeIngredient.create(recipe_id: 4, ingredient_id: 22, amount: 4, unit: "")

puts "✅ Done seeding!"
